### PR TITLE
Clean up the installing

### PR DESCRIPTION
**Pull request by CleanMachine1**

### CODE REVIEW

**Comment by CleanMachine1** [comment]
@Itai-Nelken ?

**Comment by Itai-Nelken** [comment]
sorry, I wasn't home.
did you test it? (it should work, but I want to make sure).

**Comment by CleanMachine1** [comment]
No I haven't tested however all thats changed is every .sh script now is executable, in fact it may have even fixed one as I can't remember which but 1 of the scripts wasn't given +x. I think it was g_____.sh

Give me a min and I'll find which

**Comment by CleanMachine1** [comment]
/apps/flowblade wasn't given +x

**Comment by Itai-Nelken** [comment]
thanks a lot!

**Pull request merged**
